---
- name: Setup riemann-influx-grafana
  hosts: all
  connection: local

  vars_prompt:
    - name: riemann_config_dir
      prompt: "Absolute path to the riemann config directory"
      private: no
      secure: no

  roles:
   - role: influx
   
   - role: grafana

   - role: riemann

